export const CATEGORY_TRANSLATIONS = {
  en: {
    General: "General",
    Cardiac: "Cardiac",
    Respiratory: "Respiratory",
    Neurological: "Neurological",
    Gastrointestinal: "Gastrointestinal",
    Musculoskeletal: "Musculoskeletal",
    Dermatology: "Dermatology",
    Endocrine: "Endocrine",
    MentalHealth: "Mental Health",
    Ophthalmology: "Ophthalmology",
    ENT: "ENT",
    Urology: "Urology",
    Gynecology: "Gynecology",
    Pediatrics: "Pediatrics",
    Orthopedics: "Orthopedics",
  },
  hi: {
    General: "सामान्य",
    Cardiac: "हृदय संबंधी",
    Respiratory: "श्वसन संबंधी",
    Neurological: "तंत्रिका तंत्र",
    Gastrointestinal: "पाचन तंत्र",
    Musculoskeletal: "मांसपेशी और हड्डियाँ",
    Dermatology: "त्वचा रोग",
    Endocrine: "अंतःस्रावी तंत्र",
    MentalHealth: "मानसिक स्वास्थ्य",
    Ophthalmology: "नेत्र रोग",
    ENT: "कान-नाक-गला",
    Urology: "मूत्र तंत्र",
    Gynecology: "स्त्री रोग",
    Pediatrics: "बाल रोग",
    Orthopedics: "हड्डी रोग",
  },
  ta: {
    General: "பொது",
    Cardiac: "இதயம்",
    Respiratory: "சுவாசம்",
    Neurological: "நரம்பியல்",
    Gastrointestinal: "செரிமானம்",
    Musculoskeletal: "தசை மற்றும் எலும்பு",
    Dermatology: "தோல் நோய்",
    Endocrine: "உள் சுரப்பி",
    MentalHealth: "மனநலம்",
    Ophthalmology: "கண் மருத்துவம்",
    ENT: "காது-மூக்கு-கழுத்து",
    Urology: "சிறுநீர் மருத்துவம்",
    Gynecology: "மகப்பேறு",
    Pediatrics: "குழந்தை மருத்துவம்",
    Orthopedics: "எலும்பியல்",
  },
};

export const SYMPTOMS_TRANSLATIONS = {
  en: {
    General: [
      "Fever",
      "Fatigue",
      "Weakness",
      "Loss of appetite",
      "Night sweats",
      "Chills",
      "Weight loss",
      "Malaise",
      "Swelling",
      "Dehydration",
      "Excessive sweating",
      "Paleness",
      "Generalized body pain",
    ],
    Cardiac: [
      "Chest pain",
      "Shortness of breath",
      "Palpitations",
      "Dizziness",
      "Fainting",
      "Rapid heartbeat",
      "Irregular heartbeat",
      "Swelling in legs",
      "Cold extremities",
      "Blue lips",
      "Chest pressure",
      "Orthopnea (difficulty breathing while lying down)",
    ],
    Respiratory: [
      "Cough",
      "Sore throat",
      "Wheezing",
      "Difficulty breathing",
      "Runny nose",
      "Nasal congestion",
      "Sneezing",
      "Chest tightness",
      "Bloody cough",
      "Hoarseness",
      "Stridor (noisy breathing)",
      "Rapid breathing",
    ],
    Neurological: [
      "Headache",
      "Confusion",
      "Seizures",
      "Slurred speech",
      "Numbness",
      "Tingling",
      "Weakness on one side",
      "Memory loss",
      "Tremors",
      "Loss of consciousness",
      "Dizziness",
      "Balance problems",
      "Vision problems",
      "Difficulty concentrating",
      "Sleep disturbances",
      "Facial droop",
    ],
    Gastrointestinal: [
      "Nausea",
      "Vomiting",
      "Diarrhea",
      "Loose motion",
      "Abdominal pain",
      "Constipation",
      "Heartburn",
      "Indigestion",
      "Bloating",
      "Blood in stool",
      "Loss of appetite",
      "Difficulty swallowing",
      "Acid reflux",
      "Rectal pain",
      "Black/tarry stool",
    ],
    Musculoskeletal: [
      "Joint pain",
      "Back pain",
      "Neck pain",
      "Shoulder pain",
      "Knee pain",
      "Foot pain",
      "Ankle pain",
      "Hip pain",
      "Elbow pain",
      "Wrist pain",
      "Muscle weakness",
      "Muscle pain",
      "Stiffness",
      "Swelling of joints",
      "Cramps",
      "Limited mobility",
      "Bone pain",
    ],
    Dermatology: [
      "Rash",
      "Itching",
      "Skin dryness",
      "Bruising easily",
      "Redness",
      "Swelling",
      "Hives",
      "Hair loss",
      "Acne",
      "Skin peeling",
      "Ulcers",
      "Skin darkening",
      "Skin lightening",
      "Blisters",
      "Scaly patches",
    ],
    Endocrine: [
      "Excessive thirst",
      "Frequent urination",
      "Heat intolerance",
      "Cold intolerance",
      "Weight gain",
      "Weight loss",
      "Hair thinning",
      "Sweating",
      "Increased appetite",
      "Goiter (neck swelling)",
    ],
    MentalHealth: [
      "Anxiety",
      "Depression",
      "Insomnia",
      "Irritability",
      "Mood swings",
      "Hallucinations",
      "Paranoia",
      "Loss of interest",
      "Poor concentration",
      "Social withdrawal",
      "Suicidal thoughts",
    ],
    Ophthalmology: [
      "Blurred vision",
      "Double vision",
      "Eye pain",
      "Red eyes",
      "Watery eyes",
      "Light sensitivity",
      "Loss of vision",
      "Itchy eyes",
      "Swollen eyelids",
      "Floaters",
      "Dry eyes",
    ],
    ENT: [
      "Ear pain",
      "Hearing loss",
      "Ringing in ears",
      "Vertigo",
      "Nasal blockage",
      "Postnasal drip",
      "Loss of smell",
      "Sinus pain",
      "Nosebleeds",
      "Sore mouth",
      "Swollen tonsils",
    ],
    Urology: [
      "Painful urination",
      "Blood in urine",
      "Frequent urination",
      "Urgency",
      "Incontinence",
      "Difficulty urinating",
      "Lower abdominal pain",
      "Flank pain",
      "Weak urine stream",
      "Urinary retention",
    ],
    Gynecology: [
      "Irregular periods",
      "Heavy bleeding",
      "Pelvic pain",
      "Vaginal discharge",
      "Pain during intercourse",
      "Missed period",
      "Breast tenderness",
      "Menstrual cramps",
      "Hot flashes",
    ],
    Pediatrics: [
      "Irritability in child",
      "Poor feeding",
      "Failure to thrive",
      "Developmental delay",
      "Seizures in child",
      "Persistent crying",
      "Delayed speech",
      "Recurrent infections",
      "Feeding difficulties",
    ],
    Orthopedics: [
      "Fracture",
      "Dislocation",
      "Swelling of bone",
      "Difficulty walking",
      "Stiff joints",
      "Shoulder stiffness",
      "Hip stiffness",
    ],
  },

  hi: {
    General: [
      "बुखार",
      "थकान",
      "कमज़ोरी",
      "भूख कम लगना",
      "रात को पसीना आना",
      "काँपना",
      "वज़न घटना",
      "अस्वस्थता",
      "सूजन",
      "निर्जलीकरण",
      "अत्यधिक पसीना",
      "पीला पड़ना",
      "सामान्य शरीर दर्द",
    ],
    Cardiac: [
      "सीने में दर्द",
      "सांस फूलना",
      "दिल की धड़कन महसूस होना",
      "चक्कर आना",
      "बेहोशी",
      "तेज़ दिल की धड़कन",
      "अनियमित धड़कन",
      "पैरों में सूजन",
      "हाथ-पाँव ठंडे होना",
      "नीले होंठ",
      "सीने में दबाव",
      "लेटने पर सांस लेने में कठिनाई",
    ],
    Respiratory: [
      "खाँसी",
      "गले में खराश",
      "घरघराहट",
      "सांस लेने में कठिनाई",
      "बहती नाक",
      "नाक बंद",
      "छींक आना",
      "सीने में जकड़न",
      "खून वाली खाँसी",
      "आवाज़ बैठना",
      "शोर के साथ सांस लेना",
      "तेज़ सांसें लेना",
    ],
    Neurological: [
      "सिरदर्द",
      "भ्रम",
      "दौरे पड़ना",
      "तुतलाकर बोलना",
      "सुन्नपन",
      "झुनझुनी",
      "एक तरफ़ कमजोरी",
      "स्मृति ह्रास",
      "कंपकंपी",
      "बेहोशी",
      "चक्कर आना",
      "संतुलन की समस्या",
      "दृष्टि की समस्या",
      "ध्यान केंद्रित करने में कठिनाई",
      "नींद की समस्या",
      "चेहरे का टेढ़ा होना",
    ],
    Gastrointestinal: [
      "मितली",
      "उल्टी",
      "दस्त",
      "पतले दस्त",
      "पेट दर्द",
      "कब्ज़",
      "सीने में जलन",
      "बदहज़मी",
      "पेट फूलना",
      "मल में खून",
      "भूख कम लगना",
      "निगलने में कठिनाई",
      "एसिडिटी",
      "मलाशय में दर्द",
      "काला/चिपचिपा मल",
    ],
    Musculoskeletal: [
      "जोड़ों में दर्द",
      "पीठ दर्द",
      "गर्दन दर्द",
      "कंधे में दर्द",
      "घुटने का दर्द",
      "पैर दर्द",
      "टखने का दर्द",
      "कूल्हे में दर्द",
      "कोहनी दर्द",
      "कलाई दर्द",
      "मांसपेशियों की कमजोरी",
      "मांसपेशियों का दर्द",
      "अकड़न",
      "जोड़ों की सूजन",
      "ऐंठन",
      "गतिशीलता में कमी",
      "हड्डी दर्द",
    ],
    Dermatology: [
      "चकत्ते",
      "खुजली",
      "त्वचा का सूखापन",
      "आसानी से चोट लगना",
      "लालिमा",
      "सूजन",
      "पित्ती",
      "बाल झड़ना",
      "मुँहासे",
      "त्वचा उतरना",
      "घाव",
      "त्वचा का काला होना",
      "त्वचा का हल्का होना",
      "फफोले",
      "पपड़ीदार धब्बे",
    ],
    Endocrine: [
      "अत्यधिक प्यास लगना",
      "बार-बार पेशाब आना",
      "गर्मी सहन न होना",
      "ठंड सहन न होना",
      "वज़न बढ़ना",
      "वज़न घटना",
      "बालों का पतला होना",
      "पसीना आना",
      "भूख बढ़ना",
      "गलगंड (गर्दन में सूजन)",
    ],
    MentalHealth: [
      "चिंता",
      "अवसाद",
      "अनिद्रा",
      "चिड़चिड़ापन",
      "मिज़ाज बदलना",
      "भ्रम देखना",
      "संदेह",
      "रुचि कम होना",
      "ध्यान कम लगना",
      "समाज से दूरी",
      "आत्महत्या के विचार",
    ],
    Ophthalmology: [
      "धुंधली दृष्टि",
      "दोहरी दृष्टि",
      "आँख में दर्द",
      "लाल आँखें",
      "आँसू आना",
      "रोशनी से दिक़्क़त",
      "दृष्टि ह्रास",
      "आँखों में खुजली",
      "पलकों की सूजन",
      "तैरते धब्बे",
      "सूखी आँखें",
    ],
    ENT: [
      "कान में दर्द",
      "सुनने में कमी",
      "कानों में घंटी बजना",
      "चक्कर आना",
      "नाक बंद होना",
      "नाक से बलग़म बहना",
      "सूंघने की क्षमता कम होना",
      "साइनस दर्द",
      "नाक से खून आना",
      "मुंह में छाले",
      "सूजी हुई टॉन्सिल",
    ],
    Urology: [
      "पेशाब में दर्द",
      "पेशाब में खून आना",
      "बार-बार पेशाब आना",
      "तुरंत पेशाब की ज़रूरत",
      "पेशाब पर नियंत्रण न रहना",
      "पेशाब करने में कठिनाई",
      "निचले पेट में दर्द",
      "पसलियों के पास दर्द",
      "कमज़ोर पेशाब की धार",
      "पेशाब रुकना",
    ],
    Gynecology: [
      "अनियमित मासिक धर्म",
      "अत्यधिक रक्तस्राव",
      "पेल्विक दर्द",
      "योनि स्राव",
      "संभोग के दौरान दर्द",
      "मासिक धर्म छूटना",
      "स्तनों में कोमलता",
      "मासिक धर्म में ऐंठन",
      "गर्म फ्लैशेज़",
    ],
    Pediatrics: [
      "बच्चे में चिड़चिड़ापन",
      "खाना ठीक से न खाना",
      "विकास में कमी",
      "विकास में देरी",
      "बच्चे को दौरे पड़ना",
      "लगातार रोना",
      "बोलने में देरी",
      "बार-बार संक्रमण होना",
      "खाना खाने में कठिनाई",
    ],
    Orthopedics: [
      "फ्रैक्चर",
      "हड्डी खिसकना",
      "हड्डी में सूजन",
      "चलने में कठिनाई",
      "जोड़ों में अकड़न",
      "कंधे की अकड़न",
      "कूल्हे की अकड़न",
    ],
  },

  ta: {
    General: [
      "காய்ச்சல்",
      "சோர்வு",
      "பலவீனம்",
      "பசி குறைவு",
      "இரவில் வியர்க்கும்",
      "சளி",
      "எடை குறைவு",
      "உடல் நலமின்மை",
      "வீக்கம்",
      "நீரிழப்பு",
      "அதிக வியர்வை",
      "வெண்மை",
      "உடல் வலி",
    ],
    Cardiac: [
      "மார்வலி",
      "சுவாச திணறல்",
      "இதயத் துடிப்பு",
      "தலைச்சுற்றல்",
      "மயக்கம்",
      "வேகமான இதயத் துடிப்பு",
      "ஒழுங்கற்ற இதயத் துடிப்பு",
      "கால்களில் வீக்கம்",
      "குளிர்ந்த கை, கால்",
      "நீல நிற உதடுகள்",
      "மார்பு அழுத்தம்",
      "படுக்கையில் சுவாச சிரமம்",
    ],
    Respiratory: [
      "இருமல்",
      "கழுத்து வலி",
      "விசும்பல்",
      "சுவாச சிரமம்",
      "மூக்கில் நீர் வடிதல்",
      "மூக்கு அடைப்பு",
      "தும்மல்",
      "மார்பு இறுக்கம்",
      "இரத்த இருமல்",
      "குரல் சிதைவு",
      "சத்தத்துடன் சுவாசம்",
      "வேகமான சுவாசம்",
    ],
    Neurological: [
      "தலைவலி",
      "குழப்பம்",
      "வலிப்பு",
      "தெளிவில்லாமல் பேசுதல்",
      "மயக்கம்",
      "முட்டைப்பு",
      "ஒரு பக்கம் பலவீனம்",
      "நினைவிழப்பு",
      "நடுக்கம்",
      "மயக்கம்",
      "சுற்றல்",
      "இணக்கம் பிரச்சனை",
      "பார்வை பிரச்சனை",
      "கவனம் செலுத்த சிரமம்",
      "தூக்கக் கோளாறு",
      "முகம் விலகுதல்",
    ],
    Gastrointestinal: [
      "வாந்தி உணர்ச்சி",
      "வாந்தி",
      "வயிற்றுப்போக்கு",
      "மென்மையான மலம்",
      "வயிற்று வலி",
      "வயிற்று கட்டு",
      "மனநோய்",
      "செரிமானக்கேடு",
      "வயிறு வீக்கம்",
      "மலத்தில் இரத்தம்",
      "பசி குறைவு",
      "விழுங்க சிரமம்",
      "அமிலம்",
      "குடல் வலி",
      "கருப்பு/பிசுபிசுப்பு மலம்",
    ],
    Musculoskeletal: [
      "மூட்டுவலி",
      "முதுகுவலி",
      "கழுத்துவலி",
      "தோள்வலி",
      "முழங்கால் வலி",
      "பாத வலி",
      "கணுக்கால் வலி",
      "இடுப்பு வலி",
      "முழங்கை வலி",
      "மணிக்கட்டு வலி",
      "தசை பலவீனம்",
      "தசை வலி",
      "வலிப்பு",
      "மூட்டுவீக்கம்",
      "வலிப்பு",
      "இயக்கக் குறைவு",
      "எலும்பு வலி",
    ],
    Dermatology: [
      "சுரம்",
      "அரிப்பு",
      "தோல் உலர்வு",
      "எளிதில் அடிபடுதல்",
      "சிவப்பு",
      "வீக்கம்",
      "அரிப்பு புண்கள்",
      "முடி உதிர்வு",
      "முகப்பரு",
      "தோல் உரிதல்",
      "காயம்",
      "தோல் கருமை",
      "தோல் வெளிர்வு",
      "நீர்க்கட்டி",
      "பருக்களுடன் கூடிய புள்ளிகள்",
    ],
    Endocrine: [
      "அதிக தாகம்",
      "அடிக்கடி சிறுநீர் கழித்தல்",
      "சூடு தாங்க முடியாமை",
      "குளிர் தாங்க முடியாமை",
      "எடை அதிகரித்தல்",
      "எடை குறைவு",
      "முடி மெல்லியது",
      "வியர்வை",
      "பசி அதிகரித்தல்",
      "கழுத்து வீக்கம்",
    ],
    MentalHealth: [
      "கவலை",
      "மனச்சோர்வு",
      "தூக்கமின்மை",
      "எரிச்சல்",
      "மனநிலை மாறுதல்",
      "மாயக்காட்சிகள்",
      "சந்தேகம்",
      "ஆர்வம் குறைவு",
      "கவனம் குறைவு",
      "சமூக விலகல்",
      "தற்கொலை எண்ணங்கள்",
    ],
    Ophthalmology: [
      "மங்கலான பார்வை",
      "இரட்டை பார்வை",
      "கண் வலி",
      "சிவந்த கண்கள்",
      "கண்களில் நீர்",
      "ஒளி உணர்திறன்",
      "பார்வை இழப்பு",
      "கண்களில் அரிப்பு",
      "கண்ணிமை வீக்கம்",
      "மிதக்கும் புள்ளிகள்",
      "உலர்ந்த கண்கள்",
    ],
    ENT: [
      "காது வலி",
      "கேள்வி திறன் குறைவு",
      "காதில் ஓசை",
      "சுற்றல்",
      "மூக்கு அடைப்பு",
      "மூக்கில் சளி வடிதல்",
      "மணத்தை இழத்தல்",
      "சைனஸ் வலி",
      "மூக்கில் இரத்தம்",
      "வாய் புண்கள்",
      "டான்சில் வீக்கம்",
    ],
    Urology: [
      "சிறுநீரில் வலி",
      "சிறுநீரில் இரத்தம்",
      "அடிக்கடி சிறுநீர் கழித்தல்",
      "சிறுநீர் அவசரம்",
      "சிறுநீர் கட்டுப்பாடு இழப்பு",
      "சிறுநீர் கழிக்க சிரமம்",
      "கீழ் வயிற்று வலி",
      "இடுப்பு பக்கம் வலி",
      "பலவீனமான சிறுநீர் ஓடை",
      "சிறுநீர் நின்றுவிடுதல்",
    ],
    Gynecology: [
      "அமைதியற்ற மாதவிடாய்",
      "அதிக இரத்தப்போக்கு",
      "தாழ்வரப்பில் வலி",
      "யோனி சுரப்புகள்",
      "இணக்கத்தின் போது வலி",
      "மாதவிடாய் தவறுதல்",
      "மார்பக மென்மை",
      "மாதவிடாய் வலி",
      "சூடு உணர்தல்",
    ],
    Pediatrics: [
      "குழந்தையில் எரிச்சல்",
      "சாப்பிடாதல்",
      "வளர்ச்சி குறைவு",
      "வளர்ச்சியில் தாமதம்",
      "குழந்தையில் வலிப்பு",
      "தொடர்ந்து அழுதல்",
      "பேச்சு தாமதம்",
      "அடிக்கடி தொற்று",
      "உணவு சிரமம்",
    ],
    Orthopedics: [
      "எலும்பு முறிவு",
      "எலும்பு இடைச்சல்",
      "எலும்பு வீக்கம்",
      "நடக்க சிரமம்",
      "மூட்டு இறுக்கம்",
      "தோள் இறுக்கம்",
      "இடுப்பு இறுக்கம்",
    ],
  },
};
